let express = require('express')
let router = express.Router()

let odinCController = require('../../controllers/odinC.controller')

router.get('/allusers',odinCController.allUsers)
router.get('/cities',odinCController.getAllCities)
router.get('/all_organization',odinCController.getAllOrganization)
router.get('/all_region_user',odinCController.getAllUsersByRegion)
router.get('/programm_dpo_code1c',odinCController.getProgrammDpoCode1c)
router.get('/programm_dpo',odinCController.getProgrammDpo)
router.get('/all_name_programm',odinCController.getAllNameProgramm)
router.get('/all_periods_education',odinCController.getAllPeriodsEducation)
router.get('/all_speciality_education',odinCController.getAllSpecialityEducation)
router.get('/range_cycle_time',odinCController.getRangeCycleTime)
router.get('/source_finance',odinCController.getSourceFinance)
router.get('/source_finance_withdpo',odinCController.getSourceFinanceWithdpo)
router.get('/category_edu',odinCController.getCategoryEdu)
router.get('/category_edu_withdpo',odinCController.getCategoryEduWithdpo)
router.get('/periods_education',odinCController.getPeriodsEducation)
router.get('/state_string_plan',odinCController.getStateStringPlan)
router.get('/speciality_education',odinCController.getSpecialityEducation)
router.get('/type_dpo',odinCController.getTypeDpo)
router.get('/info_programm',odinCController.getInfoProgramm)
router.get('/info_programm_test',odinCController.getInfoProgrammTest)
router.get('/info_plan_line',odinCController.getInfoPlanLine)
module.exports = router;