version: '2'
services:
  mariadb:
    image: 'docker.io/bitnami/mariadb:10.5-debian-10'
    environment:
      #- ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_ROOT_USER=root
      - MARIADB_ROOT_PASSWORD=123
      - MARIADB_USER=user
      - MARIADB_PASSWORD=123
      - MARIADB_DATABASE=lkBase
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
    ports:
      - '3306:3306'
  phpmyadmin:
    image: phpmyadmin
    links:
      - mariadb:db
    ports:
      - 9090:80
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - mariadb
    restart: always
volumes:
  mariadb_data:
    driver: local

